# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Master AI-ML Documentation | Complete Course for Technical Writers
email: contact@beingtechnicalwriter.com
description: >-
  Master AI and ML documentation with our comprehensive course. Learn to document complex AI systems, 
  explain machine learning models, and create ethical documentation for artificial intelligence. 
  Perfect for technical writers, AI engineers, and documentation specialists.
baseurl: "/aimldocumentation" # the subpath of your site, e.g. /blog
url: "https://beingtechnicalwriter.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Being Technical Writer

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
logo: /assets/images/ai-documentation-logo.png
twitter:
  username: beingtechwriter
  card: summary_large_image
facebook:
  app_id: 123456789
  publisher: https://www.facebook.com/beingtechnicalwriter
  admins: 12345678
social:
  name: Being Technical Writer
  links:
    - https://twitter.com/beingtechwriter
    - https://www.linkedin.com/in/gauravtrivedi1988/
    - https://github.com/gautriv
    - https://www.facebook.com/beingtechnicalwriter
    - https://www.youtube.com/c/beingtechnicalwriter

# Google Analytics
google_analytics: UA-123456789-1

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
      image: /assets/images/ai-documentation-social.jpg
      last_modified_at: 2023-12-01T12:00:00+00:00
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      image: /assets/images/ai-documentation-social.jpg
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/ai-documentation-social.jpg
